### ISSUE TITLE
Read-only file system error from cozy-stack

### ISSUE THREAD

**Issue by 0E9B061F** [cozy/cozy-stack#4226]
I'm running Cozy under Arch Linux. When performing various operations with `cozy-stack` I get errors saying that the filesystem is read-only. However the filesystem is writable and the `fs` location is owned and writable by the cozy user. I'm also running the `cozy-stack` commands as the cozy user.

When starting `cozy-stack.service` I get this error:

```
Nov 17 19:14:30 ArkadyIV cozy-stack[3138074]: Error: mkdir /cloud/dyn-assets: read-only file system
```

`/cloud` is located on a writable filesystem, and its permissions are correct:

```
nn@ArkadyIV / stat /cloud
  File: /cloud
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 259,2   Inode: 7602177     Links: 2
Access: (0770/drwxrwx---)  Uid: (  956/    cozy)   Gid: (  956/    cozy)
```

I can create the `dyn-assets` directory manually as the cozy user:

```
[cozy@ArkadyIV /]$ mkdir /cloud/dyn-assets
[cozy@ArkadyIV /]$ stat /cloud/dyn-assets/
  File: /cloud/dyn-assets/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 259,2   Inode: 7602178     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  956/    cozy)   Gid: (  956/    cozy)
```

And then `cozy-stack.service` does start correctly. However the problem remains and I get the same error when performing other operations:

```
[cozy@ArkadyIV /]$ cozy-stack instances add foo20485903458.example.com --apps home,settings,store
Password:*******************************
Failed to create instance for domain foo20485903458.example.com
Error: Unqualified error: mkdir /cloud/foo20485903458.example.com: read-only file system
```

My config looks like this:

```
host: 127.0.0.1
port: 8080

subdomains: nested

admin:
  host: 127.0.0.1
  port: 6060
  secret_filename: cozy-admin-passphrase

fs:
  url: file:///cloud

vault:
  credentials_encryptor_key: /etc/cozy/vault.enc
  credentials_decryptor_key: /etc/cozy/vault.dec

couchdb:
  url: http://USER:PASS@localhost:5984
konnectors:
  cmd: /usr/share/cozy/konnector-node-run.sh

log:
  level: info
  syslog: false

registries:
  default:
  - https://apps-registry.cozycloud.cc/selfhosted
  - https://apps-registry.cozycloud.cc/banks
  - https://apps-registry.cozycloud.cc/
```
